### PR TITLE
Added js functionality on cart and all product pages

### PR DESCRIPTION
**Pull request by arjun-gr**
Added js functionality to the cart and also added functionality to the products to add dynamically when clicked on add to cart. Also the prices and GST and total also gets updated as per the need, And the remove button on cart also works. Thank you for this oportunity got to learn alot while building this. The 2 js files would be cart.js and index.js

### CODE REVIEW

**Comment by nitin-pandita** [comment]
> Added js functionality to the cart and also added functionality to the products to add dynamically when clicked on add to cart. Also the prices and GST and total also gets updated as per the need, And the remove button on cart also works. Thank you for this oportunity got to learn alot while building this. The 2 js files would be cart.js and index.js

If you could add a message after clicking "add to cart", an item has been added. Will have a good impact

**Comment by arjun-gr** [comment]
i was thinking about making something like that... sure i will make it..

**Review by nitin-pandita — APPROVED** [review]
Amazing piece of work @arjun-gr . Good Job

**Comment by arjun-gr** [comment]
Thank you for this Nitin, i have learned so much that i had not learned while watching tutorials and was stuck on tutorial hell.

**Pull request merged**
